# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DlpCli < Formula
  desc ""
  homepage ""
  version "0.2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/DSGT-DLP/dlp-cli/releases/download/v0.2.0/dlp-cli_Darwin_arm64.tar.gz"
      sha256 "22fd453fa5cfda7fb3307c8b4d18785539bce5de43673f268c16648a8a8fc6f7"

      def install
        bin.install "dlp-cli"
        bash_completion.install "completions/dlp-cli.bash" => "dlp-cli"
        zsh_completion.install "completions/dlp-cli.zsh" => "_dlp-cli"
        fish_completion.install "completions/dlp-cli.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/DSGT-DLP/dlp-cli/releases/download/v0.2.0/dlp-cli_Darwin_x86_64.tar.gz"
      sha256 "5ffccfe96013d5c18c957505d80d185058e4853e41d5eeb52043a6cad5e39be2"

      def install
        bin.install "dlp-cli"
        bash_completion.install "completions/dlp-cli.bash" => "dlp-cli"
        zsh_completion.install "completions/dlp-cli.zsh" => "_dlp-cli"
        fish_completion.install "completions/dlp-cli.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/DSGT-DLP/dlp-cli/releases/download/v0.2.0/dlp-cli_Linux_x86_64.tar.gz"
      sha256 "16854763d5d8e3a2049a5128deced677c6d409c87401d682271ec8539d21a0ca"

      def install
        bin.install "dlp-cli"
        bash_completion.install "completions/dlp-cli.bash" => "dlp-cli"
        zsh_completion.install "completions/dlp-cli.zsh" => "_dlp-cli"
        fish_completion.install "completions/dlp-cli.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DSGT-DLP/dlp-cli/releases/download/v0.2.0/dlp-cli_Linux_arm64.tar.gz"
      sha256 "4d2f33fef9d34e564ab74f952a2e75708eb3d7dda59ebd8ec98b368f8a74adb2"

      def install
        bin.install "dlp-cli"
        bash_completion.install "completions/dlp-cli.bash" => "dlp-cli"
        zsh_completion.install "completions/dlp-cli.zsh" => "_dlp-cli"
        fish_completion.install "completions/dlp-cli.fish"
      end
    end
  end
end
