# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DlpCli < Formula
  desc ""
  homepage ""
  version "0.2.1-test5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/DSGT-DLP/dlp-cli/releases/download/v0.2.1-test5/dlp-cli_Darwin_x86_64.tar.gz"
      sha256 "0d1ee4067fc3e8f7aa18ae80357a233d72e8ceda30f1988ea31ad3fee5c99cb2"

      def install
        bin.install "dlp-cli"
        bash_completion.install "completions/dlp-cli.bash" => "dlp-cli"
        zsh_completion.install "completions/dlp-cli.zsh" => "_dlp-cli"
        fish_completion.install "completions/dlp-cli.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/DSGT-DLP/dlp-cli/releases/download/v0.2.1-test5/dlp-cli_Darwin_arm64.tar.gz"
      sha256 "531f93b338f77c2fcac5e70d5211783d248791c05c01c77d62330a39ef1e2d07"

      def install
        bin.install "dlp-cli"
        bash_completion.install "completions/dlp-cli.bash" => "dlp-cli"
        zsh_completion.install "completions/dlp-cli.zsh" => "_dlp-cli"
        fish_completion.install "completions/dlp-cli.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DSGT-DLP/dlp-cli/releases/download/v0.2.1-test5/dlp-cli_Linux_arm64.tar.gz"
      sha256 "751e064c61dfb7b1aa84867275811bf4dc8ae7c1355d89a9f673d44f6cf03d51"

      def install
        bin.install "dlp-cli"
        bash_completion.install "completions/dlp-cli.bash" => "dlp-cli"
        zsh_completion.install "completions/dlp-cli.zsh" => "_dlp-cli"
        fish_completion.install "completions/dlp-cli.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/DSGT-DLP/dlp-cli/releases/download/v0.2.1-test5/dlp-cli_Linux_x86_64.tar.gz"
      sha256 "b536d7b9e71629d1b2bc6e5fc5f14380853cb836783ec55a5c629962d4a26604"

      def install
        bin.install "dlp-cli"
        bash_completion.install "completions/dlp-cli.bash" => "dlp-cli"
        zsh_completion.install "completions/dlp-cli.zsh" => "_dlp-cli"
        fish_completion.install "completions/dlp-cli.fish"
      end
    end
  end
end
